version: "3.9"
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@55w0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql:/var/opt/mssql
volumes:
  mssql:
    driver: local
